version: '3'

services:
  grandet_db:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: tweb_db
    ports:
      - 5432:5432
    volumes:
      - /home/ubuntu/data/postgres:/var/lib/postgresql/data
