version: '2'

services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: iminders
      KAFKA_ZOOKEEPER_CONNECT: "godel:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "production:5:1,develop:5:1"
    volumes:
      - /etc/hosts:/etc/hosts
    container_name: kafka
