version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - './mariadb_data:/bitnami'
    restart: always
  phabricator:
    image: 'bitnami/phabricator:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    environment:
      - PHABRICATOR_HOST=${PHABRICATOR_HOST}
      - PHABRICATOR_USERNAME=${USER_NAME}
      - PHABRICATOR_PASSWORD=${PASSWD}
      - PHABRICATOR_EMAIL=${EMAIL}
      # - MARIADB_USER=root
      # - MARIADB_PASSWORD=king0123
      # - MARIADB_HOST=mariadb
      # - MARIADB_PORT_NUMBER=3306
    volumes:
      - './phabricator_data:/bitnami'
    depends_on:
      - mariadb
    restart: always
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
